name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Bazel
        run: npm install -g @bazel/bazelisk

      - name: Install dependencies
        run: npm install

      - name: Build with Bazel
        run: bazel build //...

      - name: Test with Bazel
        run: bazel test //...
